### ISSUE TITLE
apiDemo cannot run  Null exception

### ISSUE THREAD

**Issue by WxSmile** [Free-Software-for-Android/NTPSync#32]
apiDemo cannot run  Null exception

**Comment by dschuermann** [comment]
stacktrace?

**Comment by WxSmile** [comment]
04-13 17:06:35.697 8461-8761/org.ntpsync.apidemo E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                   Process: org.ntpsync.apidemo, PID: 8461
                                                                   java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                       at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:841)
                                                                    Caused by: java.lang.NullPointerException
                                                                       at org.ntpsync.apidemo.BaseActivity$4.doInBackground(BaseActivity.java:158)
                                                                       at org.ntpsync.apidemo.BaseActivity$4.doInBackground(BaseActivity.java:149)
                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                       at java.lang.Thread.run(Thread.java:841)
